language: csharp
solution: DatabaseBackupper.sln
mono: none
dotnet: 3.1.200
install:
  - dotnet restore
  - nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release DatabaseBackupper.sln
  - dotnet ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./Presentation.Tests/bin/Release/Presentation.Tests.dll